[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
select = [
  "E", # pycodestyle errors
  "F", # pyflakes
  "W", # pycodestyle warnings
  "I", # isort
]
ignore = [
]

[lint.isort]
known-first-party = ["app"]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = true
